ProjectName:
  - 二次开发的框架
  -

Env: 测试环境
# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
TesterName: BettyHuang

# 域名1
host: https://www.wanandroid.com
# 域名2，聚合接口 tst:测试环境  dev: 开发环境  internal：线上环境
jk_app_host: http://fe-acgi-v2.tst.jianke.com
# 直接请求后端，不用聚合的接口
jk_java_host: http://acgi.tst.jianke.com
# 域名3，java后端
jk_java_host2: http://setting-service.tst.jianke.com


# 平台：
platform: app
# 设备ID
x-jk-udid: BB1A9D8E-F469-4E1A-88E4-E2BA4B570038
# 版本
versionname: 6.5.3
# 版本号
versionCode: 653

# 报告通知类型：0: 不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
NotificationType: 0

# 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持返送企业微信通知
excel_report: True

# 注意点：
# 之前为了小伙伴们拉下代码执行的时候不受影响，企业微信、钉钉、邮箱的通知配置的都是我的
# 我发现很多拉代码的小伙伴这里配置都没改，所有的通知都发到我这里来了哦~~麻烦看到这里的小伙伴自己改一下相关配置

# 钉钉相关配置
DingTalk:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=a59902a7e811f93ffe301d8326b07a2acc8aa2a864e7d61ee9fc076481ced2a6
  secret: SECdea6489dfcc3b9259da943c5ae38d3530696f2fa83ac72a9ee716e9511675b9b

# 数据库相关配置
MySqlDB:
  # 数据库开关
  switch: False
  host:
  user: dev
  password:
  db: test_obp_data

# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/

# 企业通知的相关配置
WeChat:
  webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=06c028c0-6eb4-4b8c-aaff-afd5f8841683

# 邮箱通知的相关配置
email:
  send_user: 764504389@qq.com
  email_host: smtp.qq.com
  stamp_key: rzuabbobadbuhadc
  # 收件人
  send_list: 764504389@qq.com

# 飞书通知
FeiShuTalk:
  webhook:

# 实时更新用例内容，False时，已生成的代码不会在做变更
# 设置为True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: False

